// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PriceCalculationController from "./price_calculation_controller"
application.register("price-calculation", PriceCalculationController)

import SearchbarController from "./searchbar_controller"
application.register("searchbar", SearchbarController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)
